### ISSUE TITLE
Can't start Portall

### ISSUE THREAD

**Issue by DaveTSG** [need4swede/Portall#19]
Hello. I'm trying to get Portall up and running for the first time.

If I have a docker-compose.yml file with contents identical to [the example provided](https://github.com/need4swede/Portall):

```
version: '3'
services:
  portall:
    image: need4swede/portall:latest
    container_name: portall
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=myKeyGoesHere
    volumes:
      - ./instance:/app/instance
```

The container appears to be loaded, and it shows up as "healthy" in Portainer. However, loading http://192.168.4.7:8080 results in a 404 error. Ditto https.

There is nothing in the logs other than a message saying "don't use this in production".

If instead I use the docker run command, again identical to the example given:

```
docker run -p 8080:8080 \
  -e SECRET_KEY=myKeyGoesHere \
  -e PORT=8080 \
  -v ./instance:/app/instance \
  Portall
[1] 97478
bash: qr: command not found
david@docker1:~/dockerfilesNotOnNAS/portall$ "docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
^C
[1]+  Exit 1                  docker run -p 8080:8080 -e SECRET_KEY=myKeyGoesHere
```

...and that's it. Nothing loads.
Any suggestions please?

Thanks in advance.
