### ISSUE TITLE
SECRET_KEY doesn't seem to work

### ISSUE THREAD

**Issue by Becase** [need4swede/Portall#24]
hello，i use docker-compose to run portall，but the SECRET_KEY doesn't seem to work，What I mean is that I didn't use this SECRET_KEY, but was able to directly access the portall page, which caused me some trouble。
```
version: '3'

services:
  rediary:
    image: need4swede/portall:latest
    container_name: portall
    restart: unless-stopped
    ports:
      - 9174:8080
    volumes:
      - ./data:/app/instance
    environment:
      - PORT=8080
      - SECRET_KEY=3gAGC5jRZaJ
```
