### ISSUE TITLE
Not showing registered ports

### ISSUE THREAD

**Issue by morenone** [need4swede/Portall#29]
Is there any reason why it wouldn't show any registered ports? The only changes I made to the docker compose file were removing the parts about secret key and I changed the default port.

**Comment by need4swede** [comment]
@morenone 
The secret_key is used by flask, and the port mapping shouldn't be an issue.
To clarify, your `docker-compose` looks like this, just with a different port mapped?
```
version: '3'
services:
  portall:
    image: need4swede/portall:latest
    container_name: portall
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=your_secret_key
    volumes:
      - ./instance:/app/instance
  ```
