### ISSUE TITLE
labels in compose?

### ISSUE THREAD

**Issue by lephtHanded** [need4swede/Portall#44]
just a quick question:
does this read labels in compose files?

just thinking about how watchtowrr can determine to update a docker,  could portall read a definition of it's port?

or could I simply populate the predefined list.

**Comment by need4swede** [comment]
If you provide me with a sample compose file, I can demonstrate to you exactly how Portall imports the data

**Comment by lephtHanded** [comment]
here's my kara keep compose:
```
###formally hoardrr
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: always
    container_name: karakeep-app
    volumes:
      - ${DKRpath}/services/hoard:/data
      #- hoard:/data
    ports:
      - 7070:3000
    environment:
      BROWSER_WEB_URL: http://chrome:9222
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
      NEXTAUTH_SECRET: {bashed head}
      NEXTAUTH_URL: https://markers.x.y
      HOARDER_VERSION: release
      MEILI_MASTER_KEY: {sweaty fingers}
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoardweb
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: hoardsearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
volumes:
    meilisearch:
    #hoard:
       ```

**Comment by need4swede** [comment]
That compose would create one port entry, because there's only one port defined

<img width="610" alt="Image" src="https://github.com/user-attachments/assets/9e82755d-5f73-485c-b170-8b8b93dcb43d" />
<img width="1246" alt="Image" src="https://github.com/user-attachments/assets/9f639d0a-85af-49c5-aecf-b068c22e5a51" />

**Comment by lephtHanded** [comment]
thanks!
for the main app, do we just add multiple DOCKER_HOST or HOST_IP to connect to other socket_proxy's? (comma separated?)
on the main page your gif shows you dragging and dropping between multiple hosts

EDIT:
I just noticed you had an "Add IP" button.

**Comment by need4swede** [comment]
The HOST_IP variable let's you override the default IP label of the host that is running Portall. By default this is 127.0.0.1

So for example, let's say you want to see what ports services are running on from your local docker environment. Instead of them being assigned to 127.0.0.1, you can override this label by configuring your server's actual IP address instead. So it would say something like "192.168.1.50" for all your local services, instead of "127.0.0.1"

You can always use "Add IP" to manually add other hosts at any time, and configure their ports respectively.

**Comment by lephtHanded** [comment]
thanks - just tried to push it and it threw an error that it doesn't work on arm64 :(

**Comment by need4swede** [comment]
I can solve that. I'll build the images for arm and I'll let you know once they're published

**Comment by need4swede** [comment]
@lephtHanded 

In your compose file, change the image to the latest arm64 image:
```
  socket-proxy:
    image: need4swede/socket-proxy:latest-arm64

  portall:
    image: need4swede/portall:latest-arm64
```
