### ISSUE TITLE
Docker host with diffrent IP

### ISSUE THREAD

**Issue by Dracrius** [need4swede/Portall#46]
I tried about everything I can think of by changing every ip in the current docker-compose example but nothing I do will get the docker integration to display let alone use another IP other then 127.0.0.1. I'd like to map it to it's network address instead for clarity.

Love the last update btw made it easy to jump ship from portnote cause it gets really annoying working around postgres and the way that is setup. The scanning and docker support make this much more useful with my huge lists of containers.

**Comment by Dracrius** [comment]
This appears to be related to #41 where it was stated setting HOST_IP should achieve the desired effect but it does not.

**Comment by Dracrius** [comment]
```
services:
  # Init container to set up proper permissions for the database directory
  portall-init:
    image: alpine:latest
    container_name: portall-init
    command: >
      sh -c "
        echo 'Setting up instance directory permissions...'
        mkdir -p /app/instance
        chmod 777 /app/instance
        # Try to set ownership to the user that will run the main container
        chown ${USER_ID:-1000}:${GROUP_ID:-1000} /app/instance 2>/dev/null || echo 'Note: Could not change ownership (this is normal in some environments)'
        echo 'Instance directory setup complete:'
        ls -la /app/instance
        echo 'Permissions setup complete'
      "
    volumes:
      - ./instance:/app/instance
    user: 0:0 # Run as root to set permissions
    restart: no # Only run once
  # Main Portall application
  portall:
    image: need4swede/portall:latest
    container_name: portall
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    depends_on:
      - socket-proxy
      - portall-init # Wait for permissions to be set
    ports:
      - 3080:8080
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOCKER_ENABLED=true
      - HOST_IP=192.168.168.240 # Defaults to 127.0.0.1
    env_file: .env
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - portall-network
  # Docker Socket Proxy with automatic GID detection
  socket-proxy:
    image: need4swede/socket-proxy:latest
    container_name: portall-socket-proxy
    environment:
      - ALLOW_RESTARTS=0
      - ALLOW_START=0
      - ALLOW_STOP=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:2375:2375
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run/proxy
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - portall-network
networks:
  portall-network:
    driver: bridge

```

This is my current docker compose file based on the docker-compose.pull.yml. As you can see I have attempted to use said setting but it has made no difference. Docker Integration still uses 127.0.0.1.

I've tried also changing the ip listed with the ports for socket-proxy but changing that makes no difference. Dropping the IP completely from the ports for socket-proxy changes nothing so I'm not sure why 127.0.0.1 is used there at all.

I've also tried changing `- DOCKER_HOST=tcp://socket-proxy:2375` to `- DOCKER_HOST=tcp://192.168.168.240:2375` with no change. Currently despite the HOST_IP setting it doesn't appear to be used when using the docker integration.
